set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER C:/Qt/Tools/mingw1310_64/bin/gcc.exe)
set(CMAKE_CXX_COMPILER C:/Qt/Tools/mingw1310_64/bin/g++.exe)
set(CMAKE_RC_COMPILER C:/Qt/Tools/mingw1310_64/bin/windres.exe)
set(CMAKE_MAKE_PROGRAM C:/Qt/Tools/mingw1310_64/bin/mingw32-make.exe)

set(CMAKE_FIND_ROOT_PATH C:/Qt/6.10.2/mingw_64)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_PREFIX_PATH C:/Qt/6.10.2/mingw_64/lib/cmake)
set(Qt6_DIR C:/Qt/6.10.2/mingw_64/lib/cmake/Qt6)